export const dynamic = 'force-dynamic'
import configPromise from '@payload-config'
import { formatAdminURL } from 'payload/shared'

export async function GET() {
    try {
        const config = await configPromise
        const adminRoute = config.routes.admin
        const path = '/' // as generated by path: Array.isArray(params.segments) ? `/${params.segments.join('/')}` : null
        const currentRoute = formatAdminURL({ adminRoute, path })

        return Response.json({
            adminRoute,
            currentRoute,
            isMatch: currentRoute === adminRoute
        })
    } catch (error: any) {
        return Response.json({ success: false, error: error.message, stack: error.stack })
    }
}
